# ********************************************************************************
#  Copyright (c) 2024 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
# *******************************************************************************/

# Nightly-scheduled comprehensive test runs that would take too long for on-merge workflows
# Note: running the coverage job would only make sense if we use that to upload coverage info to a public platform

name: Nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      RUST_TOOLCHAIN:
        description: 'The Rust toolchain to use for the workflow'
        required: false
        default: 'stable'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read # needed for checking out the code

env:
  RUST_TOOLCHAIN: ${{ github.event.inputs.RUST_TOOLCHAIN || 'stable' }}

jobs:
  check-msrv:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Install cargo-hack
        run: cargo install --locked cargo-hack

      - name: Setup native build dependencies
        id: setup-env
        shell: bash
        run: |
          set -euo pipefail
          source "$GITHUB_WORKSPACE/.github/scripts/install-build-deps.sh"
          source "$GITHUB_WORKSPACE/.github/scripts/build-envsetup.sh"

      - name: check MSRV
        env:
          VSOMEIP_INSTALL_PATH: ${{ steps.setup-env.outputs.VSOMEIP_INSTALL_PATH }}
          ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.ARCH_SPECIFIC_CPP_STDLIB_PATH }}
          GENERIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.GENERIC_CPP_STDLIB_PATH }}
        run: |
          cargo hack check --rust-version --workspace --all-targets --ignore-private --all-features

  check-latest-deps:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Setup native build dependencies
        id: setup-env
        shell: bash
        run: |
          set -euo pipefail
          source "$GITHUB_WORKSPACE/.github/scripts/install-build-deps.sh"
          source "$GITHUB_WORKSPACE/.github/scripts/build-envsetup.sh"

      - name: Update dependencies
        run: cargo update --verbose

      - name: Run tests
        env:
          VSOMEIP_INSTALL_PATH: ${{ steps.setup-env.outputs.VSOMEIP_INSTALL_PATH }}
          ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.ARCH_SPECIFIC_CPP_STDLIB_PATH }}
          GENERIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.GENERIC_CPP_STDLIB_PATH }}
        run: |
          LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VSOMEIP_INSTALL_PATH/lib \
            cargo test --verbose --workspace --all-targets

  deny:
    uses: eclipse-uprotocol/ci-cd/.github/workflows/rust-deny-check.yaml@ad3f99eac0675c714f08c473412dae14d9fecaa8 # main
    with:
      arguments: --all-features --locked --exclude-dev

  current-spec-compliance:
    if: false # disabled until we have a SOME/IP transport spec that includes OFT specification items
    uses: eclipse-uprotocol/ci-cd/.github/workflows/requirements-tracing.yaml@ad3f99eac0675c714f08c473412dae14d9fecaa8 # main
    with:
      env-file-suffix: "oft-current"

  coverage:
    if: false # disabled for the time being because building vsomeip-sys fails as part of running tarpaulin
    name: Determine Test Coverage
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Show toolchain information
        run: |
          rustup toolchain list
          cargo --version

      - name: Install cargo-tarpaulin
        run: |
          cargo install --locked cargo-tarpaulin
          cargo tarpaulin --version

      - name: Setup native build dependencies
        id: setup-env
        shell: bash
        run: |
          set -euo pipefail
          source "$GITHUB_WORKSPACE/.github/scripts/install-build-deps.sh"
          source "$GITHUB_WORKSPACE/.github/scripts/build-envsetup.sh"

      - name: Determine code coverage
        env:
          VSOMEIP_INSTALL_PATH: ${{ steps.setup-env.outputs.VSOMEIP_INSTALL_PATH }}
          ARCH_SPECIFIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.ARCH_SPECIFIC_CPP_STDLIB_PATH }}
          GENERIC_CPP_STDLIB_PATH: ${{ steps.setup-env.outputs.GENERIC_CPP_STDLIB_PATH }}
        run: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${VSOMEIP_INSTALL_PATH}/lib
          # enable nightly features so that we can also include Doctests
          RUSTC_BOOTSTRAP=1 cargo tarpaulin \
            --workspace \
            --no-fail-fast \
            --all-targets \
            --doc --tests \
            -o xml -o lcov -o html

      - name: Upload coverage report (xml)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test Coverage Results (xml)
          path: cobertura.xml

      - name: Upload coverage report (lcov)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test Coverage Results (lcov)
          path: lcov.info

      - name: Upload coverage report (html)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test Coverage Results (html)
          path: tarpaulin-report.html
